name: Firebase Continuous Deployment

on:
  push:
    branches: [ master, mujbranch ]     #blabla


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
      - uses: firebase deploy --token [FIREBASE_TOKEN] --only hosting --non-interactive #w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: GitHub Actions test