name: CI/CD + Firebase deployment

on:
  push:
    branches: [ master, mujbranch ]     

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting --non-interactive 
        
        
        #with:
         # args: deploy --only hosting
        #env:
         # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          #FIREBASE_PROJECT: GitHub Actions test
      
        