name: CI/CD + Firebase deployment
#
on:
  push:
    branches:
      - master
      - mujbranch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: CI and Build
      run: |
        npm ci
        npm run build
    - name: Firebase Deploy
      run: |
        npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        