name: CI/CD + Firebase deployment

on:
  push:
    branches: [ master, mujbranch ]     

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
      - run: firebase deploy --token=1//030vViCn0Bvc3CgYIARAAGAMSNwF-L9Ir-3D4BIYKGmBTPZqngQIJ6AazD5g6lUi900SlLexkB3jp7m-_BCLFOfv3yA-9uXFG2dw  
        
        
        #with:
         # args: deploy --only hosting
        #env:
         # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          #FIREBASE_PROJECT: GitHub Actions test
      
        